# Generated by Django 5.1.2 on 2024-10-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="balance_sheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cash", models.FloatField()),
                ("property", models.FloatField()),
                ("accounts_payable", models.FloatField()),
                ("loan_payable", models.FloatField()),
                ("unrestricted_net_assets", models.FloatField()),
                ("restricted_net_assets", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="bugeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program_name", models.CharField(max_length=100)),
                ("budgeted_amount", models.FloatField()),
                ("actual_spent", models.FloatField()),
                ("remaining_balance", models.FloatField()),
                ("notes", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="donor_management",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("donor_name", models.CharField(max_length=100)),
                ("donation_date", models.DateField()),
                ("total_amount", models.FloatField()),
                ("allocated_amount", models.FloatField()),
                ("remaining_balance", models.FloatField()),
                ("reciept_issued", models.DateField()),
                ("followup_date", models.DateField()),
                ("form_required", models.BooleanField()),
                ("acknowledgment_letter_sent", models.BooleanField()),
                ("notes", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="funding_accounting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=100)),
                ("restricted", models.BooleanField()),
                ("total_amount", models.FloatField()),
                ("allocated_amount", models.FloatField()),
                ("remaining_balance", models.FloatField()),
                ("restrictions", models.CharField(max_length=500)),
                ("notes", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="grant_tracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("grantor", models.CharField(max_length=100)),
                ("grant_amount", models.FloatField()),
                ("allocated", models.FloatField()),
                ("remaining", models.FloatField()),
                ("restrictions", models.CharField(max_length=100)),
                ("due_date", models.DateField()),
                ("notes", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="income_statement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revenue_source", models.CharField(max_length=100)),
                ("unrestricted_funds", models.FloatField()),
                ("restricted_funds", models.FloatField()),
                ("total", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="irs_fillings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filling_type", models.CharField(max_length=100)),
                ("due_date", models.DateField()),
                ("status", models.CharField(max_length=100)),
                ("notes", models.CharField(max_length=100)),
            ],
        ),
    ]
